server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  data:
    redis:
      host: rideupmicroredis-hung2307xuan-bff7.f.aivencloud.com
      port: 27742
      username: default
      password: AVNS_w8vWRSdFiTovQJ277R8
      timeout: 10s
      ssl:
        enabled: true

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service # dùng service name đăng ký với Eureka
          predicates:
            - Path=/api/identity/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# JWT Configuration
jwt:
  signerKey: S5eUx6DQSJ3ce3Dokj+qZmVlpj3hG7M841wX3NEj3oMcPwx6+oOA9AdHzbZE3Nb84

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
