spring:
  application:
    name: location-service


  datasource:
    url: jdbc:mysql://localhost:3306/location_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: Hung23072004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: rideupmicroredis-hung2307xuan-bff7.f.aivencloud.com
      port: 27742
      username: default
      password: AVNS_w8vWRSdFiTovQJ277R8
      timeout: 10s
      ssl:
        enabled: true
  cache:
    type: redis


  cloud:
    openfeign:
      client:
        config:
          location-service:
            connect-timeout: 5000
            read-timeout: 10000

server:
  port: 8082
  servlet:
    context-path: /api/location

jwt:
  signerKey: S5eUx6DQSJ3ce3Dokj+qZmVlpj3hG7M841wX3NEj3oMcPwx6+oOA9AdHzbZE3Nb84
  valid-duration: 36000
  refreshable-duration: 360000

expiryTime: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  frontend-base-url: http://localhost:5173

location:
  seeding:
    enabled: true
    max-retries: 3
    initial-backoff-ms: 1500