spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/payment_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Hung23072004}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: rideupmicroredis-hung2307xuan-bff7.f.aivencloud.com
      port: 27742
      username: default
      password: AVNS_w8vWRSdFiTovQJ277R8
      timeout: 10s
      ssl:
        enabled: true

  cache:
    type: redis


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      enable-auto-commit: false
      group-id: ${KAFKA_GROUP_PAYMENT:payment-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual_immediate
      observation-enabled: true
    template:
      observation-enabled: true
    retry:
      topic:
        enabled: true
        attempts: 4
        delay: 2000
        multiplier: 1.5
        dlt-enabled: true

server:
  port: 8085
  servlet:
    context-path: /api/payment

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.orm.deprecation: ERROR
    com.netflix: ERROR
    org.apache.kafka: WARN

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  kafka:
    topics:
      payment-requested: ${KAFKA_TOPIC_PAYMENT_REQUESTED:booking.payment.requested}
      payment-completed: ${KAFKA_TOPIC_PAYMENT_COMPLETED:payment.completed}
      payment-failed: ${KAFKA_TOPIC_PAYMENT_FAILED:payment.failed}
      payment-authorized: ${KAFKA_TOPIC_PAYMENT_AUTHORIZED:payment.authorized}
      booking-cancell-request: ${KAFKA_TOPIC_BOOKING_CANCELL_REQUEST:booking.cancell.request}
      booking-approved: ${KAFKA_TOPIC_BOOKING_APPROVED:booking.approved}
      booking-rejected: ${KAFKA_TOPIC_BOOKING_REJECTED:booking.rejected}
      refund-completed: ${KAFKA_TOPIC_REFUND_COMPLETED:refund.completed}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51Tnh1VCbDzrK5kTtPdqB66FbuczyHnM4J9p5jDYzjHjFS80KVyAxeDfcXBYczHQy1D77tAsswJrhfAc16Jz8p5Ur00Fq2FtFt2}
