spring:
  application:
    name: notification-service


  datasource:
    url: jdbc:mysql://localhost:3306/notification_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: Hung23072004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: rideupmicroredis-hung2307xuan-bff7.f.aivencloud.com
      port: 27742
      username: default
      password: AVNS_w8vWRSdFiTovQJ277R8
      timeout: 10s
      ssl:
        enabled: true
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: hungabc2307@gmail.com
    password: kblwzwaamhqyokjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_GROUP_NOTIFICATION:notification-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8086
  servlet:
    context-path: /api/notification

jwt:
  signerKey: S5eUx6DQSJ3ce3Dokj+qZmVlpj3hG7M841wX3NEj3oMcPwx6+oOA9AdHzbZE3Nb84
  valid-duration: 36000
  refreshable-duration: 360000

expiryTime: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

supabase:
  url: https://tgbtragwxkulpittcjzw.supabase.co
  api-key: sb_secret_J_fc93TeUV2CNFWJPh0aVQ_fYGfDwnZ
  bucket: Ride_Up_Micro


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}



app:
  frontend-base-url: http://localhost:5173
  clients:
    booking:
      base-url: http://localhost:8084/api/booking
    trip:
      base-url: http://localhost:8083/api/trip
  kafka:
    topics:
      booking-confirmed: ${KAFKA_TOPIC_BOOKING_CONFIRMED:booking.confirmed}
      booking-cancelled: ${KAFKA_TOPIC_BOOKING_CANCELLED:booking.cancelled}
